version: '3.8'

services:
  app:
    container_name: firebase-shopping-cart-app
    build:
      context: .
      dockerfile: Dockerfile
      target: ${DOCKER_TARGET:-development} # Use 'production' for production builds
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    container_name: firebase-shopping-cart-redis
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  redis-data:
