version: '3.9'

services:
  app:
    container_name: firebase-shopping-cart-app
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: ${DOCKER_TARGET:-development}
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - redis
      - maildev

  redis:
    container_name: firebase-shopping-cart-redis
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  maildev:
    container_name: firebase-shopping-cart-maildev
    image: maildev/maildev
    ports:
      - '1080:1080'
      - '1025:1025'

volumes:
  redis-data:
