version: '3.9'

services:
  app:
    container_name: ring-cart-app
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - '3000:3000'
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      # - NODE_OPTIONS=--max-old-space-size=4096
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./package.json
    depends_on:
      - redis
      - maildev

  redis:
    container_name: ring-cart-redis
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  maildev:
    container_name: ring-cart-maildev
    image: maildev/maildev
    ports:
      - '1080:1080'
      - '1025:1025'

volumes:
  app_node_modules:
  redis-data:
