# Base stage - common dependencies
FROM node:22-alpine AS base
WORKDIR /app
COPY package.json package-lock.json ./

RUN npm install

# Copy the rest of the project
COPY . .

# ----------------------------------
# Development  Stage
# ----------------------------------
FROM base AS dev
ENV NODE_ENV=development
EXPOSE 3000
CMD ["npm", "run", "dev"]
